apiVersion: v1
kind: Service
metadata:
  name: reddit-service
spec:
  selector:
    app: reddit-app
  type: LoadBalancer  # Change NodePort to LoadBalancer
  ports:
    - protocol: TCP
      port: 80         # external port
      targetPort: 8000 # matches containerPort

      # nodePort: 30007  # Or let Kubernetes choose (by omitting nodePort)



