apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-app
  template:
    metadata:
      labels:
        app: reddit-app
    spec:
      containers:
      - name: reddit-container
        image: us-west2-docker.pkg.dev/reddit-app-458322/reddit-docker-repo/reddit-fastapi:latest
        ports:
          - containerPort: 8000

